# Read the master username + password generated by the secrets module.
# secret_string is JSON: { "username": "...", "password": "..." }.
data "aws_secretsmanager_secret_version" "rds_master" {
  secret_id = var.rds_master_secret_arn
}

locals {
  rds_creds = jsondecode(data.aws_secretsmanager_secret_version.rds_master.secret_string)
}

# Empty ingress on purpose. The compute module (API + Lambda worker) will
# attach itself by adding aws_security_group_rule resources that reference
# this SG's ID — that way we don't have to reach into compute from here, and
# the DB stays unreachable until something explicitly opens a path to it.
resource "aws_security_group" "rds" {
  name        = "medical-ai-rds-${var.environment}"
  description = "Postgres ingress for the medical-ai DB. Ingress rules added by callers."
  vpc_id      = var.vpc_id

  tags = {
    Name = "medical-ai-rds-${var.environment}"
  }
}

resource "aws_db_parameter_group" "main" {
  name        = "medical-ai-${var.environment}-pg16"
  family      = "postgres16"
  description = "Postgres 16 params: pgvector preload, force TLS, slow-query + DDL logging."

  # pgvector needs to be loaded at server start. Static parameter — RDS reboots
  # to apply, which Terraform handles automatically on the first apply.
  parameter {
    name         = "shared_preload_libraries"
    value        = "pg_stat_statements,vector"
    apply_method = "pending-reboot"
  }

  # Reject non-TLS connections at the server. Defense in depth — the SG only
  # admits VPC sources, but we don't want any plaintext on the wire either.
  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }

  # Log schema changes for audit. Do NOT set log_statement = all — that would
  # log every SELECT, including PHI in WHERE clauses.
  parameter {
    name  = "log_statement"
    value = "ddl"
  }

  # Anything slower than 1s gets logged — catches missing indexes early.
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }
}

resource "aws_db_instance" "main" {
  identifier = "medical-ai-${var.environment}"

  engine         = "postgres"
  engine_version = "16.4"
  instance_class = var.instance_class

  db_name  = var.db_name
  username = local.rds_creds.username
  password = local.rds_creds.password
  port     = 5432

  # Network placement — data subnets only, no public IP.
  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false
  multi_az               = var.multi_az

  # Storage. gp3 is the modern default. Autoscaling lets storage grow
  # automatically up to max_allocated_storage.
  storage_type          = "gp3"
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_encrypted     = true
  kms_key_id            = var.app_key_arn

  # Custom parameter group for pgvector + force_ssl.
  parameter_group_name = aws_db_parameter_group.main.name

  # Backups + maintenance — windows are UTC, picked to be off-hours in IST.
  backup_retention_period = var.backup_retention_period
  backup_window           = var.backup_window
  maintenance_window      = var.maintenance_window
  copy_tags_to_snapshot   = true

  # Apply minor-version patches automatically during the maintenance window.
  # Major versions (16 → 17) are always manual.
  auto_minor_version_upgrade = true

  # Destroy semantics. Prod: take a final snapshot and refuse delete by
  # default. Staging: skip the snapshot so we can rebuild fast.
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "medical-ai-${var.environment}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  # The password is in Terraform state regardless of where we sourced it.
  # Suppress diff so a future rotation in Secrets Manager doesn't force a
  # spurious "password changed" plan — rotation happens by updating the
  # secret and then running ModifyDBInstance manually.
  lifecycle {
    ignore_changes = [password]
  }
}
