# Read the AUTH token generated by the secrets module. The redis token is a
# plain string (not JSON) — the secrets module stored it as random_password.result
# directly, no jsonencode wrapping.
data "aws_secretsmanager_secret_version" "redis_auth_token" {
  secret_id = var.redis_auth_token_secret_arn
}

# Empty ingress on purpose — same pattern as the rds module. Compute + bastion
# add their own ingress rules referencing this SG by ID.
resource "aws_security_group" "redis" {
  name        = "medical-ai-redis-${var.environment}"
  description = "Redis ingress for the medical-ai cache. Ingress rules added by callers."
  vpc_id      = var.vpc_id

  tags = {
    Name = "medical-ai-redis-${var.environment}"
  }
}

# Redis 7 parameter group family.
resource "aws_elasticache_parameter_group" "main" {
  name        = "medical-ai-redis-${var.environment}-r7"
  family      = "redis7"
  description = "Cache eviction policy override. Defaults to noeviction which is wrong for a cache."

  # Default is noeviction — Redis refuses writes when memory is full. For a
  # cache we want LRU eviction across the whole keyspace. Every value we
  # store has a TTL, but evictions still happen when memory fills before
  # TTLs expire.
  parameter {
    name  = "maxmemory-policy"
    value = "allkeys-lru"
  }
}

resource "aws_elasticache_replication_group" "main" {
  replication_group_id = "medical-ai-${var.environment}"
  description          = "Sessions + rate limits for medical-ai-${var.environment}. NO PHI."

  engine         = "redis"
  engine_version = var.engine_version
  node_type      = var.node_type
  port           = 6379

  # Single replication group, cluster mode disabled. num_cache_clusters here
  # means "number of nodes in the group" — confusing AWS argument name.
  num_cache_clusters         = var.num_cache_clusters
  automatic_failover_enabled = var.automatic_failover_enabled
  multi_az_enabled           = var.multi_az_enabled

  # Network placement — data subnets only.
  subnet_group_name  = var.elasticache_subnet_group_name
  security_group_ids = [aws_security_group.redis.id]

  # Parameter group — applies eviction policy override.
  parameter_group_name = aws_elasticache_parameter_group.main.name

  # Encryption: at rest via our CMK, in transit via TLS. AUTH token required
  # when transit encryption is on. Clients must speak TLS.
  at_rest_encryption_enabled = true
  kms_key_id                 = var.app_key_arn
  transit_encryption_enabled = true
  auth_token                 = data.aws_secretsmanager_secret_version.redis_auth_token.secret_string

  # Snapshots — light. Cache is recoverable from app logic; the 1-day window
  # is for rollback after an accidental FLUSHDB, not for compliance.
  snapshot_retention_limit = var.snapshot_retention_limit
  snapshot_window          = var.snapshot_window

  # Apply minor-version patches in the maintenance window.
  maintenance_window         = var.maintenance_window
  auto_minor_version_upgrade = true

  # Match the RDS pattern — AUTH rotation is a deliberate two-step process
  # (update secret + modify-replication-group), not a side effect of apply.
  lifecycle {
    ignore_changes = [auth_token]
  }
}
